config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments
  end

  resources :users do 
    resources :posts
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :post, presence: true
  validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, :dependent => :destroy

	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :create, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    comment = comment_params.merge!({"user_id" => current_user.id})
    @comment = @post.comments.create(comment)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js { @comment_content = render_to_string(partial: 'comment', locals: { comment: @comment })}
         
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[:"#{flash_type}"] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<!-- /row -->
<div class="row">
  <div class="col-sm-1">
    <div class="thumbnail">
      <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
    </div>
    <!-- /thumbnail -->
  </div>
  <!-- /col-sm-1 -->
  <div class="col-sm-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong><%= User.find(comment.user_id).email %></strong> <span class="text-muted">commented <%= time_ago_in_words(comment.created_at)%></span>
        <% if current_user && comment.user_id == current_user.id %>
          <label> &nbsp; &nbsp;<i class="fa fa-pencil"></i></label>
        <% end -%>
      </div>
      <div class="panel-body">
        <%= raw comment.body %>
      </div>
      <!-- /panel-body -->
    </div>
    <!-- /panel panel-default -->
  </div>
  <!-- /col-sm-5 -->
</div>
<!-- /row -->

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("<%= raw escape_javascript(@comment_content)%>").hide().appendTo(".comment").fadeIn(500);
$("#comment_body").val("")

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <% if current_user && post.user.id == current_user.id%>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    


<%= render partial: 'shared/header' %>
    
<div id="main-wrapper">
  <div id="content-wrapper">
      <%= flash_messages %>
      <% if params[:controller].to_s.include?('devise') %>
          <div class="container">
              <div class="row">
                <div class="col-md-6 col-md-offset-3" style="margin-top: 50px;">
                    <%= yield %>
                </div>   
              </div>
          </div>

      <% else %>
          <div class="container js--ct-body">
            <div class="row">
              <%= yield %>

            </div>
          </div>
      <% end %>
    </div>
</div> <!-- / #content-wrapper -->
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for([current_user,@post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control', rows:'5' %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :disable_with => 'Submiting...', class: 'btn btn-primary' %>
    <%= link_to 'cancel', posts_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>Editing Post</h3>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
<div class="container">
  <% @posts.each do |post| %>
    <div class="well">
        <div class="media">
        <a class="pull-left" href="#">
          <%= image_tag("sticky-post.png")%>
        </a>
        <div class="media-body">
          <h4 class="media-heading"><%= post.title %></h4>
            <p class="text-right">post by <%= User.find(post.user_id).email %></p>
            <!-- <p><%= raw post.body%></p> -->
            <ul class="list-inline list-unstyled">
          <li><span><i class="fa fa-calendar"></i>&nbsp;&nbsp;<%= time_ago_in_words(post.created_at)%></span></li>
              <li>|</li>
              <span><i class="fa fa-comments"></i>&nbsp;&nbsp;<%= post.comments.count %> <%= link_to 'comments', post %></span>
              <% if user_signed_in? && current_user.id == post.user_id%>
                <li>|</li>
                  <span><i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;<%= link_to 'Edit', edit_post_path(post) %></span>
                <li>|</li>
                  <span><i class="fa fa-trash-o"></i>&nbsp;&nbsp;<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
              <% end -%>
        </ul>
         </div>
      </div>
    </div>
  <% end -%>
  <%= link_to 'New Post', new_post_path, class:'btn btn-primary' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="well">
    <div class="media">
    <a class="pull-left" href="#">
      <%= image_tag("sticky-post.png")%>
    </a>
    <div class="media-body">
      <h4 class="media-heading"><%= @post.title %></h4>
        <p class="text-right">post by <%= User.find(@post.user_id).email %></p>
        <p><%= raw @post.body%></p>
        <ul class="list-inline list-unstyled">
          <li><span><i class="fa fa-calendar"></i>&nbsp;&nbsp;<%= time_ago_in_words(@post.created_at)%></span></li>
          <li>|</li>
          <li><span><i class="fa fa-comments"></i>&nbsp;&nbsp;<%= @post.comments.count %> <%= link_to 'comments', @post %></span></li>
          <% if user_signed_in? && current_user.id == @post.user_id%>
            <li>|</li>
              <li><span><i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;<%= link_to 'Edit', edit_post_path(@post) %></span></li>
            <li>|</li>
              <li><span><i class="fa fa-trash-o"></i>&nbsp;&nbsp;<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %></span></li>
          <% end -%>
        </ul>
        <!-- Comment -->
        <h4>Comments</h4>
        <div class="comment">
          <%= render @post.comments %>
        </div>
        <h4>Add a comment:</h4>
        <div class="tab-pane" id="add-comment">
            <%= form_for [@post, @post.comments.build], html: { remote:true, role: 'form', class: 'form-horizontal'} do |f| %> 
                <div class="form-group">
                    
                    <div class="col-sm-10">
                      <%= f.text_area :body, class: 'form-control', rows:"5" %>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10" style="margin:0px;">                    
                        <button class="btn btn-success btn-circle text-uppercase" type="submit" id="submitComment"><span><i class="fa fa-paper-plane-o"></i></span> Summit comment</button>
                    </div>
                </div>            
            <% end -%>
        </div>
   </div>
  </div>
</div>
<%= link_to 'Back', posts_path, class: 'btn btn-primary' %>
<!-- <p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<h2>Add a comment:</h2>
<%= form_for [@post, @post.comments.build], html: { remote:true} do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %> -->

app/views/shared/_header.html.erb
<div class="right clearfix header">
  <% if current_user %>
    <div class="col-md-9">
      <ul class="nav nav-pills">
        <li role="presentation" class="active"><%= link_to("home", posts_path)%></li>
      </ul>
    </div>
  <% end -%>
  <div class="col-md-3" style="float:right">
    <ul class="nav navbar-nav pull-right right-navbar-nav">
      <% if current_user %>
        <li><%= link_to(raw("<i class='fa fa-user'></i>&nbsp;#{current_user.email}")) %></li>
        <li><%= link_to(raw('<i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out'), destroy_user_session_path, :method => :delete) %></li>     
      <% else %>
        <li><%= link_to(raw('<i class="fa fa-sign-in"></i>&nbsp;&nbsp;Login'), new_user_session_path) %></li>    
      <% end %>
    </ul>       
  </div>
 <!-- / .navbar-nav -->
</div> <!-- / .right -->